<h3> 1. 텐서 초기화 </h3>

In [1]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [2]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지하며 1로 선언
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"Ones Tensor : \n {x_ones} \n")
print(f'Random Tensor : \n {x_rand} \n')

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.4935, 0.3103],
        [0.9873, 0.8954]]) 



In [3]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor : \n {ones_tensor} \n')
print(f'Zeros Tensor : \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.7037, 0.3464, 0.5915],
        [0.2270, 0.4647, 0.5410]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [4]:
tensor = torch.rand(3, 4)
print(f'Shape of Tensors : {tensor.shape}')
print(f'DataType of Tensors : {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of Tensors : torch.Size([3, 4])
DataType of Tensors : torch.float32
Device tensor is stored on: cpu


In [6]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f'Device tensor is stored on : {tensor.device}')

Device tensor is stored on : cuda:0


In [11]:
tensor = torch.rand(4, 4)
print(f'Tensor : {tensor}')
print(f'First row : {tensor[0]}')
print(f'First column : {tensor[:, 0]}')
print(f'Last column : {tensor[..., -1]}') #tensor[:, -1]이랑 같음

Tensor : tensor([[0.4217, 0.9880, 0.6915, 0.0631],
        [0.3870, 0.2513, 0.4033, 0.4031],
        [0.6836, 0.0287, 0.5789, 0.7945],
        [0.7544, 0.4793, 0.0380, 0.1277]])
First row : tensor([0.4217, 0.9880, 0.6915, 0.0631])
First column : tensor([0.4217, 0.3870, 0.6836, 0.7544])
Last column : tensor([0.0631, 0.4031, 0.7945, 0.1277])


In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[0.4217, 0.9880, 0.6915, 0.0631, 0.4217, 0.9880, 0.6915, 0.0631, 0.4217,
         0.9880, 0.6915, 0.0631],
        [0.3870, 0.2513, 0.4033, 0.4031, 0.3870, 0.2513, 0.4033, 0.4031, 0.3870,
         0.2513, 0.4033, 0.4031],
        [0.6836, 0.0287, 0.5789, 0.7945, 0.6836, 0.0287, 0.5789, 0.7945, 0.6836,
         0.0287, 0.5789, 0.7945],
        [0.7544, 0.4793, 0.0380, 0.1277, 0.7544, 0.4793, 0.0380, 0.1277, 0.7544,
         0.4793, 0.0380, 0.1277]])


In [31]:
# 두 텐서 간의 행렬 곱을 계산함
data = [[1, -2], [2, -2]]
tensor = torch.tensor(data)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f'tensor @ tensor.T : {y1}')
print(f'tensor.matmul(tensor.T) : {y2}')

y3 = torch.zeros_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

# 요소별 곱도 가능
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor, dtype = torch.float)
torch.mul(tensor, tensor, out = z3)

tensor @ tensor.T : tensor([[5, 6],
        [6, 8]])
tensor.matmul(tensor.T) : tensor([[5, 6],
        [6, 8]])


tensor([[1., 4.],
        [4., 4.]])

In [35]:
# 텐서의 모든 값을 하나로 집계함
agg = tensor.sum()
agg_item = agg.item() ## 하나만 있으면 item 이용해서 추출 가능
print(f'agg의 type : {type(agg)}')
print(f'agg_item의 type : {type(agg_item)}')

agg의 type : <class 'torch.Tensor'>
agg_item의 type : <class 'int'>


In [37]:
## in_place 연산도 가능
print(f'{tensor}\n')
tensor.add_(5) ## in_place에서 연산 진행
print(tensor)

tensor([[6, 3],
        [7, 3]])

tensor([[11,  8],
        [12,  8]])


In [39]:
t = torch.ones(5)
print(f't : {t}')
n = t.numpy()
print(f'n : {n}')

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [41]:
## 텐서와 넘파이는 메모리 공간을 공유하기 때문에 하나를 바꾸면 다른 하나로 바뀜
t.add_(1)
print(f't : {t}')
print(f'n : {n}')

t : tensor([3., 3., 3., 3., 3.])
n : [3. 3. 3. 3. 3.]


In [42]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out = n)

print(f't : {t}')
print(f'n : {n}')

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
